image: node

cache:
  paths:
    - node_modules

stages:
  - install
  - lint
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - yarn install

lint:
  stage: lint
  needs: [install]
  script:
    - yarn lint

test:
  stage: test
  needs: [install]
  script:
    - yarn coverage

build:
  stage: build
  needs: [test, lint]
  artifacts:
    paths:
      - dist
  script:
    - yarn build

deploy:
  stage: deploy
  needs: [build]
  when: manual
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - main
