image: node

cache:
  paths:
    - node_modules

stages:
  - install
  - lint
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - npm install

lint:
  stage: lint
  needs: [install]
  script:
    - npm run lint

test:
  stage: test
  needs: [install]
  script:
    - npm run coverage
  coverage: '/All files\s+\|\s+\d+\.\d+/'
  artifacts:
    paths:
      - coverage

build:
  stage: build
  needs: [test, lint]
  artifacts:
    paths:
      - dist
  script:
    - npm run build

deploy:
  stage: deploy
  needs: [build]
  when: manual
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - main
